### ISSUE TITLE
Vue Router 的页面过渡动效问题

### ISSUE THREAD

**Issue by Subilan** [sotapmc/Monologue#1]
在 `@/views/Admin.vue` 中，有一个 `<router-view/>` 用于管理管理员页面的子路由，在路由文件有如下定义

```typescript
// at @/router/index.ts
const routes = [
        {
		path: "/admin",
		name: "admin",
		component: () => import("@/views/Admin.vue"),
		children: [
			{
				path: "panel",
				name: "admin-panel",
				component: () => import("@/views/AdminPanel.vue")
			},
			{
				path: "auth",
				name: "admin-auth",
				component: () => import("@/views/AdminAuth.vue")
			},
			{
				path: "new-event",
				name: "admin-new-event",
				component: () => import("@/views/AdminNewEvent.vue")
			},
			{
				path: "edit-event/:id?",
				name: "admin-edit-event",
				component: () => import("@/views/AdminNewEvent.vue")
			}
		]
	}
]
```

在这个 `router-view` 上面嵌套了一个 `transition` 用于添加页面的过渡动画，目前用的是最普通的 opacity 淡入淡出。

```less
/* at @/views/Admin.vue */
.fade-enter {
  visibility: hidden;
  opacity: 0;
}

.fade-leave-to {
  display: none;
}

.fade-enter-active, .fade-leave-active {
  transition: opacity .4s ease;
}

.fade-enter-to, .fade-leave {
  opacity: 1;
  visibility: visible;
}
```

这个时候引出了遇到的第一个问题

## 在路由切换时出现很长的滚动条（已解决 ✅）

当点击切换时，会出现很长的滚动条占用一部分宽度，导致整个页面向左抖动，每次都只是一瞬间（也就是在 transition 里面设置的 .4s），很不美观。思考了一下原因之后，决定把 transition 的时间调整到 60s 进行诊断。

最后发现，vue-router 实现这个的原理是在切换的时候出现两个视图，一个是先前的视图，作为 leave，一个是后面的视图，作为 enter。

所以，我将 `.fade-leave-to` 这个规则设定为 `display: none` 后就解决了这个问题，**但这也带来的第二个或许更为严重的问题。**

## JavaScript 动态追加元素内容的 CSS 渲染延迟问题（未解决 ❌）

添加了 `display: none` 之后，原来的情况似乎消失了，但是在下一秒又回来了。这个时候我又将 transition 的时间调整到了更长的 100s 进行分析。

但是和之前不同的是，之前那种情况将时间延长以后，滚动条会持续出现，而且向下滑动是可以看到第二个视图的。通过个人的逻辑思维很容易得出，设置 `display: none` 将下面的视图隐藏即可解决。

但是，这次点击之后，即使是 100s 的时长，滚动条也只是一瞬间的出现。无论将 transition 中的时间调成多久，滚动条都只是一瞬间。在这个时长之间，我还可以观察到被设置为 `display: none` 的视图的确不存在了。

那么这里我就推断，也许 `display: none` 的确生效了，但是由于这个切换是动态的，因此元素的 CSS 渲染存在着一定的延迟，导致最开始不存在 display 属性，后来才被应用。
